### ISSUE TITLE
Section 2 - Subsection 2.1 Product Perspective

### ISSUE THREAD

**Issue by gagefulwood** [citlalih1421/Group3-SE#11]
Describe the context and origin of the product being specified in this SRS. For example, state whether this product is a follow-on member of a product family, a replacement for certain existing systems, or a new, self-contained product. If the SRS defines a component of a larger system, relate the requirements of the larger system to the functionality of this software and identify interfaces between the two. A simple diagram that shows the major components of the overall system, subsystem interconnections, and external interfaces can be helpful.

**Comment by citlalih1421** [comment]
Section 2.1 completed. Review at your earliest convinience.
