### ISSUE TITLE
Section 2 - Subsection 2.2 Product Functions

### ISSUE THREAD

**Issue by gagefulwood** [citlalih1421/Group3-SE#12]
Summarize the major functions the product must perform or must let the user perform. Details will be provided in Section 3, so only a high level summary (such as a bullet list) is needed here. Organize the functions to make them understandable to any reader of the SRS. A picture of the major groups of related requirements and how they relate, such as a top level data flow diagram or object class diagram, is often effective.

**Comment by jmt880** [comment]
Gage Fulwood, I will start working on this now.
