### ISSUE TITLE
Section 2 - Subsection 2.4 Operating Environment

### ISSUE THREAD

**Issue by gagefulwood** [citlalih1421/Group3-SE#14]
Describe the environment in which the software will operate, including the hardware platform, operating system and versions, and any other software components or applications with which it must peacefully coexist.

**Comment by yas27s** [comment]
2.4 operating environments

- Windows 10+, Linux, MacOS
- Chrome-based
- HTML, CSS, JavaScript, SQLite, and Python

![image](https://github.com/citlalih1421/Group3-SE/assets/130023668/70732b16-cc5d-4c58-94aa-f64e8732bb63)

(Image references)

Front end: https://images.app.goo.gl/E9UTZQeUHSvGqFMp7

Back end: https://images.app.goo.gl/7Zxz8VbWfRKAHzrd8

Application: https://images.app.goo.gl/rKCnnJhfaZF9rQaT7

Client: https://images.app.goo.gl/WLaZS2QmYK9obTn6A

Server: https://images.app.goo.gl/7dY4EV7vy7QvyQ8s7

SQL: https://www.google.com/imgres?imgurl=https%3A%2F%2Fwww.ibm.com%2Fcontent%2Fdam%2Fadobe-cms%2Finstana%2Fmedia_logo%2FAzure-SQL-Database-Monitoring.component.complex-narrative-xl.ts%3D1688044945966.png%2Fcontent%2Fadobe-cms%2Fus%2Fen%2Fproducts%2Finstana%2Fsupported-technologies%2Fazure-sql-database-monitoring%2F_jcr_content%2Froot%2Ftable_of_contents%2Fbody%2Fcontent_section_styled%2Fcontent-section-body%2Fcomplex_narrative%2Flogoimage&tbnid=b7JDQE4Ygd_iNM&vet=12ahUKEwii5IChzJCEAxXiobAFHa5dBMMQMygKegUIARCKAQ..i&imgrefurl=https%3A%2F%2Fwww.ibm.com%2Fproducts%2Finstana%2Fsupported-technologies%2Fazure-sql-database-monitoring&docid=CEvCqdr5y5TajM&w=640&h=359&q=sql&hl=en-us&client=safari&ved=2ahUKEwii5IChzJCEAxXiobAFHa5dBMMQMygKegUIARCKAQ

**Comment by citlalih1421** [comment]
Finished.
