### ISSUE TITLE
Section 4 - Subsection 4.4 Software Quality Attributes

### ISSUE THREAD

**Issue by gagefulwood** [citlalih1421/Group3-SE#27]
Specify any additional quality characteristics for the product that will be important to either the customers or the developers. Some to consider are: adaptability, availability, correctness, flexibility, interoperability, maintainability, portability, reliability, reusability, robustness, testability, and usability. Write these to be specific, quantitative, and verifiable when possible. At the least, clarify the relative preferences for various attributes, such as ease of use over ease of learning.

**Comment by citlalih1421** [comment]
Done.
