### ISSUE TITLE
Section 1 - Subsection 1.1 Purpose

### ISSUE THREAD

**Issue by gagefulwood** [citlalih1421/Group3-SE#3]
Identify the product whose software requirements are specified in this document, including the revision or release number. Describe the scope of the product that is covered by this SRS, particularly if this SRS describes only part of the system or a single subsystem.

**Comment by jmt880** [comment]
Gage Fulwood, I have my first draft and will also be committing to this branch (SRS-Documentation-Section-1).

**Comment by jmt880** [comment]
hello
