### ISSUE TITLE
Section 1 - Subsection 1.3 Intended Audience

### ISSUE THREAD

**Issue by gagefulwood** [citlalih1421/Group3-SE#6]
Describe the different types of reader that the document is intended for, such as developers, project managers, marketing staff, users, testers, and documentation writers. Describe what the rest of this SRS contains and how it is organized. Suggest a sequence for reading the document, beginning with the overview sections and proceeding through the sections that are most pertinent to each reader type.

**Comment by Blacksmith822** [comment]
Finished, text me if it needs any changes
